// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ0w6gsbUS3Uex2UL9aKW7qRmKLDxCtZ0',
    appId: '1:22515697054:web:039a0f4a98533ca4eac28f',
    messagingSenderId: '22515697054',
    projectId: 'survey-akademik',
    authDomain: 'survey-akademik.firebaseapp.com',
    storageBucket: 'survey-akademik.firebasestorage.app',
    measurementId: 'G-K0QD0E41WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiYP_aTWRhE4L8WHr8_K8EUFlHDV2xhA',
    appId: '1:22515697054:android:d29d2a82a8513c68eac28f',
    messagingSenderId: '22515697054',
    projectId: 'survey-akademik',
    storageBucket: 'survey-akademik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_y3vd1CP_XYEe69QrrKUz6WYegIJNdOA',
    appId: '1:22515697054:ios:e0e87b148a473de3eac28f',
    messagingSenderId: '22515697054',
    projectId: 'survey-akademik',
    storageBucket: 'survey-akademik.firebasestorage.app',
    iosBundleId: 'com.example.surveyAkademik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_y3vd1CP_XYEe69QrrKUz6WYegIJNdOA',
    appId: '1:22515697054:ios:e0e87b148a473de3eac28f',
    messagingSenderId: '22515697054',
    projectId: 'survey-akademik',
    storageBucket: 'survey-akademik.firebasestorage.app',
    iosBundleId: 'com.example.surveyAkademik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ0w6gsbUS3Uex2UL9aKW7qRmKLDxCtZ0',
    appId: '1:22515697054:web:14fc5931c4d650afeac28f',
    messagingSenderId: '22515697054',
    projectId: 'survey-akademik',
    authDomain: 'survey-akademik.firebaseapp.com',
    storageBucket: 'survey-akademik.firebasestorage.app',
    measurementId: 'G-MNG33CG26L',
  );

}